name: Build and deploy Python app to Azure Web App

# env:
#   AZURE_WEBAPP_NAME: deploybetaanalyis  # set this to the name of your Azure Web App
#   PYTHON_VERSION: '3.11'              # set this to the Python version to use

on:
  push:
    branches: [ "Main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: deploybetaanalyis
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
